steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "functions",
        "deploy",
        "cloud-monitoring-notifier",
        "--region=asia-northeast1",
        "--source=.",
        "--trigger-topic=cloud-monitoring-notifier",
        "--runtime=python311",
        "--memory=128M",
        "--entry-point=monitoring_notify",
        "--update-env-vars=[WEBHOOK_URL=${_WEBHOOK_URL},ICON_IMAGE_URL=${_ICON_IMAGE_URL}]",
        "--service-account=discord-bot@slackbot-288310.iam.gserviceaccount.com",
      ]
